backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)
media_folder: "_site/assets/post-images"
public_folder: "/assets/post-images"

collections:
  - name: "latest-news"
    label: "Latest News"
    folder: "src/pages/blogs/latest-news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags (Add `lnsNew` for the post to show on the home page.)", name: "tags", widget: "list", default: ["lnsAll"] }

      - { label: "First Featured Image", name: "image1", widget: "image" }
      - { label: "First Image Caption", name: "imageAlt1", widget: "string" }

      - { label: "Body", name: "body", widget: "markdown" }

  - name: "latest-speeches-and-press-releases"
    label: "Latest Speeches and Press Releases"
    folder: "src/pages/blogs/latest-speeches-and-press-releases"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags (Add `lsprNew` for the post to show on the home page.)", name: "tags", widget: "list", default: ["lsprAll"] }

      - { label: "First Featured Image", name: "image1", widget: "image" }
      - { label: "First Image Caption", name: "imageAlt1", widget: "string" }

      - { label: "Body", name: "body", widget: "markdown" }

  - name: "featured-videos"
    label: "Featured Videos"
    folder: "src/pages/blogs/featured-videos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Paste emded youtube link", name: "link", widget: "string"}
      - { label: "Tags (Add `fvNew` for the post to show on the home page.)", name: "tags", widget: "list", default: ["fvAll"] }